volumes:
  data:
    external: true
networks:
  avsnetwork:
    driver: bridge
services:
  avsmongo:
    image: mongo
    networks: 
      - avsnetwork
    environment:
      - MONGO_INITDB_ROOT_USERNAME="admin"
      - MONGO_INITDB_ROOT_PASSWORD="pass"
    volumes:
      - data:/data/db
  avsmongoexpress:
    image: mongo-express
    networks:
      - avsnetwork
    environment:
      - ME_CONFIG_MONGODB_SERVER=avsmongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - 8082:8081
    depends_on: 
      - avsmongo
  avsapimongo:
    image: bluesamuel/avs-api-mongo:v2
    networks: 
      - avsnetwork
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://admin:pass@avsmongo:27017/"
    ports: 
      - 8085:3000
    depends_on: 
      - avsmongoexpress
  
